In [19]:
import pandas as pd

In [20]:
Alcaldias_csv = "Alcaldia_Precio_m2.csv"
Alcaldias_df = pd.read_csv(Alcaldias_csv)

In [21]:
del Alcaldias_df['Unnamed: 0']
Alcaldias_df.head(16)

                 Alcaldias  Precio por metro cuadrado
0                   Tlapan                       6667
1           Alvaro Obregon                      20714
2             Azcapotzalco                      17255
3               Xochimilco                       6278
4    Cuajimalpa de Morelos                      13725
5         Gustavo A Madero                      14545
6               Iztapalapa                       9960
7           Miguel Hidalgo                      46193
8                  Tlahuac                       7000
9               Cuauhtemoc                      45037
10           Benito Juarez                      44167
11                Coyoacan                      27000
12  La Magdalena Contreras                      12678
13              Milpa Alta                        980
14               Iztacalco                      16949
15     Venustiano Carranza                      18251

In [22]:
population_csv = "population.csv"
population_df = pd.read_csv(population_csv)

In [23]:
population_df.head()

,Clave de entidad federativa,Nombre de la entidad,Clave de municipio,Nombre del municipio,Clave de localidad,Nombre de la localidad,Latitud,Longitud,Poblacion total,Poblacion 15 a 17,Poblacion 18 a 24,Poblacion 15 a 17 que asiste a la escuela,Poblacion 18 a 24 que asiste a la escuela,Grado promedio de escolaridad,Total de viviendas,Total de viviendas habitadas
0,9,Distrito Federal,2,Azcapotzalco,1,Azcapotzalco,192858.0,991100.0,414711.0,18922.0,47181.0,15904.0,22237.0,10.80,132135.0,117264.0
1,9,Distrito Federal,3,Coyoacán,1,Coyoacán,192100.0,990942.0,620416.0,26665.0,69383.0,22072.0,36164.0,11.66,195589.0,180946.0
2,9,Distrito Federal,4,Cuajimalpa de Morelos,1,Cuajimalpa de Morelos,192228.0,991705.0,160491.0,8304.0,20523.0,6296.0,7534.0,10.42,47346.0,41708.0
3,9,Distrito Federal,4,Cuajimalpa de Morelos,10,Cruz Blanca,191906.0,991924.0,581.0,49.0,87.0,37.0,20.0,7.69,165.0,137.0
4,9,Distrito Federal,4,Cuajimalpa de Morelos,20,San Lorenzo Acopilco,191944.0,991932.0,23037.0,1316.0,3078.0,955.0,966.0,9.17,6024.0,5510.0

In [24]:
population_df = population_df.rename(columns={"Nombre del municipio": "Alcaldias"})
population_df.head()

,Clave de entidad federativa,Nombre de la entidad,Clave de municipio,Alcaldias,Clave de localidad,Nombre de la localidad,Latitud,Longitud,Poblacion total,Poblacion 15 a 17,Poblacion 18 a 24,Poblacion 15 a 17 que asiste a la escuela,Poblacion 18 a 24 que asiste a la escuela,Grado promedio de escolaridad,Total de viviendas,Total de viviendas habitadas
0,9,Distrito Federal,2,Azcapotzalco,1,Azcapotzalco,192858.0,991100.0,414711.0,18922.0,47181.0,15904.0,22237.0,10.80,132135.0,117264.0
1,9,Distrito Federal,3,Coyoacán,1,Coyoacán,192100.0,990942.0,620416.0,26665.0,69383.0,22072.0,36164.0,11.66,195589.0,180946.0
2,9,Distrito Federal,4,Cuajimalpa de Morelos,1,Cuajimalpa de Morelos,192228.0,991705.0,160491.0,8304.0,20523.0,6296.0,7534.0,10.42,47346.0,41708.0
3,9,Distrito Federal,4,Cuajimalpa de Morelos,10,Cruz Blanca,191906.0,991924.0,581.0,49.0,87.0,37.0,20.0,7.69,165.0,137.0
4,9,Distrito Federal,4,Cuajimalpa de Morelos,20,San Lorenzo Acopilco,191944.0,991932.0,23037.0,1316.0,3078.0,955.0,966.0,9.17,6024.0,5510.0

In [26]:
alcaldias_merge_df = pd.merge(population_df, data_alcaldias_df, on="Alcaldias")
alcaldias_merge_df.head()

,Clave de entidad federativa,Nombre de la entidad,Clave de municipio,Alcaldias,Clave de localidad,Nombre de la localidad,Latitud,Longitud,Poblacion total,Poblacion 15 a 17,Poblacion 18 a 24,Poblacion 15 a 17 que asiste a la escuela,Poblacion 18 a 24 que asiste a la escuela,Grado promedio de escolaridad,Total de viviendas,Total de viviendas habitadas,Precio por metro cuadrado
0,9,Distrito Federal,2,Azcapotzalco,1,Azcapotzalco,192858.0,991100.0,414711.0,18922.0,47181.0,15904.0,22237.0,10.80,132135.0,117264.0,17255
1,9,Distrito Federal,4,Cuajimalpa de Morelos,1,Cuajimalpa de Morelos,192228.0,991705.0,160491.0,8304.0,20523.0,6296.0,7534.0,10.42,47346.0,41708.0,13725
2,9,Distrito Federal,4,Cuajimalpa de Morelos,10,Cruz Blanca,191906.0,991924.0,581.0,49.0,87.0,37.0,20.0,7.69,165.0,137.0,13725
3,9,Distrito Federal,4,Cuajimalpa de Morelos,20,San Lorenzo Acopilco,191944.0,991932.0,23037.0,1316.0,3078.0,955.0,966.0,9.17,6024.0,5510.0,13725
4,9,Distrito Federal,4,Cuajimalpa de Morelos,50,La Venta,192005.0,991838.0,531.0,35.0,73.0,22.0,20.0,8.78,128.0,123.0,13725

In [27]:
alcaldias_merge_df.to_csv('metro2xcolonia.csv')